AWSTemplateFormatVersion: 2010-09-09
Description: This template creates the resources of an SP-API application
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: SP-API Default Configuration
        Parameters:
          - ClientId
          - ClientSecret
          - RefreshToken
          - RegionCode
      - Label:
          default: Sample Solution Configuration
        Parameters:
          - ProgrammingLanguage
          - RandomSuffix
          - ArtifactsS3BucketName
          - LambdaFunctionsCodeS3Key
          - SPAPIProcessNotificationLambdaFunctionHandler
          - SPAPISubscribeNotificationsLambdaFunctionHandler
          - SPAPICreateQueryLambdaFunctionHandler
          - SPAPICancelQueryLambdaFunctionHandler
          - SPAPIGetDocumentLambdaFunctionHandler
          - SPAPIStoreDocumentLambdaFunctionHandler
    ParameterLabels:
      ClientId:
        default: Client Id
      ClientSecret:
        default: Client Secret
      RefreshToken:
        default: Refresh Token
      RegionCode:
        default: Region Code
      ProgrammingLanguage:
        default: Programming Language
      RandomSuffix:
        default: Random suffix
      ArtifactsS3BucketName:
        default: Artifacts S3 Bucket Name
      LambdaFunctionsCodeS3Key:
        default: Lambda Functions Code S3 Key
      StepFunctionsStateMachineDefinitionS3Key:
        default: Step Functions State Machine Definition S3 Key
      SPAPIProcessNotificationLambdaFunctionHandler:
        default: Handler of Process Notification Lambda Function
      SPAPISubscribeNotificationsLambdaFunctionHandler:
        default: Handler of Subscribe Notifications Lambda Function
      SPAPICreateQueryLambdaFunctionHandler:
        default: Handler of Creating Query Lambda Function
      SPAPICancelQueryLambdaFunctionHandler:
        default: Handler of Canceling Query Lambda Function
      SPAPIGetDocumentLambdaFunctionHandler:
        default: Handler Getting Document information Lambda Function
      SPAPIStoreDocumentLambdaFunctionHandler:
        default: Handler of Storing Document information Lambda Function
Parameters:
  ClientId:
    Type: String
    MinLength: 1
    Description: Client Id of the SP-API app
    NoEcho: true
  ClientSecret:
    Type: String
    MinLength: 1
    Description: Client Secret of the SP-API app
    NoEcho: true
  RefreshToken:
    Type: String
    MinLength: 1
    Description: Refresh Token used for testing the SP-API app
    NoEcho: true
  RegionCode:
    Type: String
    MinLength: 1
    Description: Region Code used for testing the SP-API app
    NoEcho: true
  ProgrammingLanguage:
    Type: String
    MinLength: 1
    Description: Programming language of the Lambda functions
    AllowedValues:
      - java11
      - nodejs18.x
      - python3.8
      - dotnet6
  RandomSuffix:
    Type: String
    MinLength: 6
    MaxLength: 12
    Description: Random suffix to append to generated resources
  ArtifactsS3BucketName:
    Type: String
    MinLength: 1
    Description: Name of the S3 bucket containing the application's artifacts
  LambdaFunctionsCodeS3Key:
    Type: String
    MinLength: 1
    Description: Key of the S3 file containing the Lambda functions code
  SPAPICreateQueryLambdaFunctionHandler:
    Type: String
    MinLength: 1
    Description: Handler of Creating the Query Lambda Function
  SPAPICancelQueryLambdaFunctionHandler:
    Type: String
    MinLength: 1
    Description: Handler of Canceling the Query Lambda Function
  SPAPIProcessNotificationLambdaFunctionHandler:
    Type: String
    MinLength: 1
    Description: Handler of Process Notification Lambda Function
  SPAPISubscribeNotificationsLambdaFunctionHandler:
    Type: String
    MinLength: 1
    Description: Handler of Subscribe Notifications Lambda Function
  SPAPIGetDocumentLambdaFunctionHandler:
    Type: String
    MinLength: 1
    Description: Handler of Getting Document information Lambda Function
  SPAPIStoreDocumentLambdaFunctionHandler:
    Type: String
    MinLength: 1
    Description: Handler of Storing Document information Lambda Function
  StepFunctionsStateMachineDefinitionS3Key:
    Type: String
    MinLength: 1
    Description: Key of the S3 file containing the Step Functions state machine definition
Resources:
  SPAPIAppCredentials:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Join
        - '-'
        - - SPAPIAppCredentials
          - !Ref RandomSuffix
      Description: Secret containing SP-API app credentials
      SecretString: !Sub
        - >-
          {"AppClientId": "${AppClientIdValue}", "AppClientSecret":
          "${AppClientSecretValue}"}
        - AppClientIdValue: !Ref ClientId
          AppClientSecretValue: !Ref ClientSecret
  SPAPICreateQueryLambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: !Join
        - '-'
        - - SPAPICreateQueryLambdaFunction
          - !Ref RandomSuffix
      Description: Create the GraphQL Query Lambda Function
      Code:
        S3Bucket: !Ref ArtifactsS3BucketName
        S3Key: !Ref LambdaFunctionsCodeS3Key
      Handler: !Ref SPAPICreateQueryLambdaFunctionHandler
      Role: !GetAtt
        - SPAPILambdaExecutionRole
        - Arn
      Runtime: !Ref ProgrammingLanguage
      MemorySize: 512
      Timeout: 60
      Environment:
        Variables:
          REFRESH_TOKEN: !Ref RefreshToken
          REGION_CODE: !Ref RegionCode
          SP_API_APP_CREDENTIALS_SECRET_ARN: !Ref SPAPIAppCredentials
  SPAPICancelQueryLambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: !Join
        - '-'
        - - SPAPICancelQueryLambdaFunction
          - !Ref RandomSuffix
      Description: Cancel the GraphQL Query Lambda Function
      Code:
        S3Bucket: !Ref ArtifactsS3BucketName
        S3Key: !Ref LambdaFunctionsCodeS3Key
      Handler: !Ref SPAPICancelQueryLambdaFunctionHandler
      Role: !GetAtt
        - SPAPILambdaExecutionRole
        - Arn
      Runtime: !Ref ProgrammingLanguage
      MemorySize: 512
      Timeout: 60
      Environment:
        Variables:
          REFRESH_TOKEN: !Ref RefreshToken
          REGION_CODE: !Ref RegionCode
          SP_API_APP_CREDENTIALS_SECRET_ARN: !Ref SPAPIAppCredentials
  SPAPIProcessNotificationLambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: !Join
        - '-'
        - - SPAPIProcessNotificationLambdaFunction
          - !Ref RandomSuffix
      Description: Process Notifications Lambda function
      Code:
        S3Bucket: !Ref ArtifactsS3BucketName
        S3Key: !Ref LambdaFunctionsCodeS3Key
      Handler: !Ref SPAPIProcessNotificationLambdaFunctionHandler
      Role: !GetAtt
        - SPAPINotificationsLambdaExecutionRole
        - Arn
      Runtime: !Ref ProgrammingLanguage
      MemorySize: 512
      Timeout: 60
      Environment:
        Variables:
          STATE_MACHINE_ARN: !Ref SPAPIStateMachine
  SPAPISubscribeNotificationsLambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: !Join
        - '-'
        - - SPAPISubscribeNotificationsLambdaFunction
          - !Ref RandomSuffix
      Description: Subscribe Notifications Lambda function
      Code:
        S3Bucket: !Ref ArtifactsS3BucketName
        S3Key: !Ref LambdaFunctionsCodeS3Key
      Handler: !Ref SPAPISubscribeNotificationsLambdaFunctionHandler
      Role: !GetAtt
        - SPAPILambdaExecutionRole
        - Arn
      Runtime: !Ref ProgrammingLanguage
      MemorySize: 512
      Timeout: 60
      Environment:
        Variables:
          REFRESH_TOKEN: !Ref RefreshToken
          REGION_CODE: !Ref RegionCode
          SP_API_APP_CREDENTIALS_SECRET_ARN: !Ref SPAPIAppCredentials
          SQS_QUEUE_ARN: !GetAtt
            - SPAPINotificationsQueue
            - Arn
  SPAPIGetDocumentLambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: !Join
        - '-'
        - - SPAPIGetDocumentLambdaFunction
          - !Ref RandomSuffix
      Description: Get Document information Lambda Function
      Code:
        S3Bucket: !Ref ArtifactsS3BucketName
        S3Key: !Ref LambdaFunctionsCodeS3Key
      Handler: !Ref SPAPIGetDocumentLambdaFunctionHandler
      Role: !GetAtt
        - SPAPILambdaExecutionRole
        - Arn
      Runtime: !Ref ProgrammingLanguage
      MemorySize: 512
      Timeout: 60
      Environment:
        Variables:
          REFRESH_TOKEN: !Ref RefreshToken
          REGION_CODE: !Ref RegionCode
          SP_API_APP_CREDENTIALS_SECRET_ARN: !Ref SPAPIAppCredentials
  SPAPIStoreDocumentLambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: !Join
        - '-'
        - - SPAPIStoreDocumentLambdaFunction
          - !Ref RandomSuffix
      Description: Store Document information Lambda Function
      Code:
        S3Bucket: !Ref ArtifactsS3BucketName
        S3Key: !Ref LambdaFunctionsCodeS3Key
      Handler: !Ref SPAPIStoreDocumentLambdaFunctionHandler
      Role: !GetAtt
        - SPAPIStoreDocumentLambdaExecutionRole
        - Arn
      Runtime: !Ref ProgrammingLanguage
      MemorySize: 512
      Timeout: 60
      Environment:
        Variables:
          QUERY_ITEMS_TABLE_NAME: !Ref SPAPIQueryItemsTable
          DATAKIOSK_DOCUMENTS_S3_BUCKET_NAME: !Ref SPAPIDataKioskDocumentsS3Bucket
  SPAPILambdaExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Join
        - '-'
        - - SPAPILambdaExecutionRole
          - !Ref RandomSuffix
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - !Sub 'arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      Policies:
        - PolicyName: SecretsReaderPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: 'secretsmanager:GetSecretValue'
                Resource:
                  - !Ref SPAPIAppCredentials
  SPAPIStoreDocumentLambdaExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Join
        - '-'
        - - SPAPIStoreDocumentLambdaExecutionRole
          - !Ref RandomSuffix
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - !Sub 'arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      Policies:
        - PolicyName: DynamoDBWriterPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: 'dynamodb:PutItem'
                Resource: !GetAtt
                  - SPAPIQueryItemsTable
                  - Arn
        - PolicyName: S3Policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 's3:PutObject'
                Resource: !Sub
                  - '${BucketArn}/*'
                  - BucketArn: !GetAtt
                      - SPAPIDataKioskDocumentsS3Bucket
                      - Arn
  SPAPINotificationsLambdaExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Join
        - '-'
        - - SPAPINotificationsLambdaExecutionRole
          - !Ref RandomSuffix
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - !Sub 'arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      Policies:
        - PolicyName: SQSReaderPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'SQS:DeleteMessage'
                  - 'SQS:GetQueueAttributes'
                  - 'SQS:ReceiveMessage'
                Resource: !GetAtt
                  - SPAPINotificationsQueue
                  - Arn
        - PolicyName: StepFunctionsPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'states:StartExecution'
                Resource: !Ref SPAPIStateMachine
  SPAPINotificationsDeadLetterQueue:
    Type: 'AWS::SQS::Queue'
    Properties:
      QueueName: !Join
        - '-'
        - - sp-api-notifications-dead-letter-queue
          - !Ref RandomSuffix
      VisibilityTimeout: 60
  SPAPINotificationsQueue:
    Type: 'AWS::SQS::Queue'
    Properties:
      QueueName: !Join
        - '-'
        - - sp-api-notifications-queue
          - !Ref RandomSuffix
      VisibilityTimeout: 60
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt
          - SPAPINotificationsDeadLetterQueue
          - Arn
        maxReceiveCount: 3
  SPAPINotificationsEventSourceMapping:
    Type: 'AWS::Lambda::EventSourceMapping'
    Properties:
      BatchSize: 1
      Enabled: true
      EventSourceArn: !GetAtt
        - SPAPINotificationsQueue
        - Arn
      FunctionName: !GetAtt
        - SPAPIProcessNotificationLambdaFunction
        - Arn
  SPAPINotificationsQueuePolicy:
    Type: 'AWS::SQS::QueuePolicy'
    Properties:
      Queues:
        - !Ref SPAPINotificationsQueue
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - 'SQS:SendMessage'
              - 'SQS:GetQueueAttributes'
            Resource: !GetAtt
              - SPAPINotificationsQueue
              - Arn
            Principal:
              AWS:
                - '437568002678'
  SPAPIQueryItemsTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: !Join
        - '-'
        - - SPAPIQueryItemsTable
          - !Ref RandomSuffix
      AttributeDefinitions:
        - AttributeName: AccountId
          AttributeType: S
        - AttributeName: QueryId
          AttributeType: S
      KeySchema:
        - AttributeName: AccountId
          KeyType: HASH
        - AttributeName: QueryId
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
  SPAPIDataKioskDocumentsS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
      BucketName: !Join
        - '-'
        - - sp-api-dk-documents-s3-bucket
          - !Ref RandomSuffix
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
  SPAPIStateMachine:
    Type: 'AWS::StepFunctions::StateMachine'
    Properties:
      StateMachineName: !Join
        - '-'
        - - SPAPIStateMachine
          - !Ref RandomSuffix
      StateMachineType: STANDARD
      DefinitionS3Location:
        Bucket: !Ref ArtifactsS3BucketName
        Key: !Ref StepFunctionsStateMachineDefinitionS3Key
      DefinitionSubstitutions:
        GetDocumentLambdaFunctionArn: !GetAtt
          - SPAPIGetDocumentLambdaFunction
          - Arn
        StoreDocumentLambdaFunctionArn: !GetAtt
          - SPAPIStoreDocumentLambdaFunction
          - Arn
      RoleArn: !GetAtt
        - SPAPIStateMachineExecutionRole
        - Arn
  SPAPIStateMachineExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: LambdaInvokePolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'lambda:InvokeFunction'
                Resource:
                  - !GetAtt
                    - SPAPIGetDocumentLambdaFunction
                    - Arn
                  - !GetAtt
                    - SPAPIStoreDocumentLambdaFunction
                    - Arn