AWSTemplateFormatVersion: 2010-09-09
Description: This template creates the resources of an SP-API application
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: SP-API Default Configuration
        Parameters:
          - ClientId
          - ClientSecret
          - RefreshToken
      - Label:
          default: Sample Solution Configuration
        Parameters:
          - ProgrammingLanguage
          - RandomSuffix
          - ArtifactsS3BucketName
          - LambdaFunctionsCodeS3Key
          - SPAPISolicitationSchedulerHandler
          - SPAPIGetSolicitationActionsHandler
          - SPAPISubmitSolicitationHandler
          - SPAPISubscribeNotificationsHandler
          - StepFunctionsStateMachineDefinitionS3Key
    ParameterLabels:
      ClientId:
        default: Client Id
      ClientSecret:
        default: Client Secret
      RefreshToken:
        default: Refresh Token
      ProgrammingLanguage:
        default: Programming Language
      RandomSuffix:
        default: Random suffix
      ArtifactsS3BucketName:
        default: Artifacts S3 Bucket Name
      LambdaFunctionsCodeS3Key:
        default: Lambda Functions Code S3 Key
      SPAPISolicitationSchedulerHandler:
        default: Handler of SP-API Solicitation Scheduler Lambda Function
      SPAPIGetSolicitationActionsHandler:
        default: Handler of SP-API Get Solicitation Actions Lambda Function
      SPAPISubmitSolicitationHandler:
        default: Handler of SP-API Submit Solicitation Lambda Function
      SPAPISubscribeNotificationsHandler:
        default: Handler of SP-API Subscribe Notifications Lambda Function
      StepFunctionsStateMachineDefinitionS3Key:
        default: Step Functions State Machine Definition S3 Key
Parameters:
  ClientId:
    Type: String
    MinLength: 1
    Description: Client Id of the SP-API app
    NoEcho: true
  ClientSecret:
    Type: String
    MinLength: 1
    Description: Client Secret of the SP-API app
    NoEcho: true
  RefreshToken:
    Type: String
    MinLength: 1
    Description: Refresh Token used for testing the SP-API app
    NoEcho: true
  ProgrammingLanguage:
    Type: String
    MinLength: 1
    Description: Programming language of the Lambda functions
    AllowedValues:
      - java11
      - nodejs18.x
      - python3.8
      - dotnet6
  RandomSuffix:
    Type: String
    MinLength: 6
    MaxLength: 12
    Description: Random suffix to append to generated resources
  ArtifactsS3BucketName:
    Type: String
    MinLength: 1
    Description: Name of the S3 bucket containing the application's artifacts
  LambdaFunctionsCodeS3Key:
    Type: String
    MinLength: 1
    Description: Key of the S3 file containing the Lambda functions code
  SPAPISolicitationSchedulerHandler:
    Type: String
    MinLength: 1
    Description: Handler of SP-API Solicitation Scheduler Lambda Function
  SPAPIGetSolicitationActionsHandler:
    Type: String
    MinLength: 1
    Description: Handler of SP-API Get Solicitation Actions Lambda Function
  SPAPISubmitSolicitationHandler:
    Type: String
    MinLength: 1
    Description: Handler of SP-API Submit Solicitation Lambda Function
  SPAPISubscribeNotificationsHandler:
    Type: String
    MinLength: 1
    Description: Handler of SP-API Subscribe Notifications Lambda Function
  StepFunctionsStateMachineDefinitionS3Key:
    Type: String
    MinLength: 1
    Description: Key of the S3 file containing the Step Functions state machine definition
Resources:
  SPAPIAppCredentials:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Join
        - '-'
        - - SPAPIAppCredentials
          - !Ref RandomSuffix
      Description: Secret containing SP-API app credentials
      SecretString: !Sub
        - >-
          {"AppClientId": "${AppClientIdValue}", "AppClientSecret":
          "${AppClientSecretValue}"}
        - AppClientIdValue: !Ref ClientId
          AppClientSecretValue: !Ref ClientSecret
  SPAPISolicitationSchedulerLambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: !Join
        - '-'
        - - SPAPISolicitationScheduler
          - !Ref RandomSuffix
      Description: SP-API Solicitation Scheduler Lambda function
      Code:
        S3Bucket: !Ref ArtifactsS3BucketName
        S3Key: !Ref LambdaFunctionsCodeS3Key
      Handler: !Ref SPAPISolicitationSchedulerHandler
      Role: !GetAtt
        - SPAPISolicitationSchedulerLambdaExecutionRole
        - Arn
      Runtime: !Ref ProgrammingLanguage
      MemorySize: 512
      Timeout: 60
      Environment:
        Variables:
          SOLICITATIONS_SCHEDULER_ROLE_ARN: !GetAtt
            - SPAPISolicitationsSchedulerRole
            - Arn
          SOLICITATIONS_STATE_MACHINE_ARN: !Ref SPAPIStateMachine
  SPAPIGetSolicitationActionsLambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: !Join
        - '-'
        - - SPAPIGetSolicitationActions
          - !Ref RandomSuffix
      Description: SP-API Get Solicitation Actions Lambda function
      Code:
        S3Bucket: !Ref ArtifactsS3BucketName
        S3Key: !Ref LambdaFunctionsCodeS3Key
      Handler: !Ref SPAPIGetSolicitationActionsHandler
      Role: !GetAtt
        - SPAPIGetSolicitationActionsLambdaExecutionRole
        - Arn
      Runtime: !Ref ProgrammingLanguage
      MemorySize: 512
      Timeout: 60
      Environment:
        Variables:
          SP_API_APP_CREDENTIALS_SECRET_ARN: !Ref SPAPIAppCredentials
          REFRESH_TOKEN: !Ref RefreshToken
  SPAPISubmitSolicitationLambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: !Join
        - '-'
        - - SPAPISubmitSolicitation
          - !Ref RandomSuffix
      Description: SP-API Submit Solicitation Lambda function
      Code:
        S3Bucket: !Ref ArtifactsS3BucketName
        S3Key: !Ref LambdaFunctionsCodeS3Key
      Handler: !Ref SPAPISubmitSolicitationHandler
      Role: !GetAtt
        - SPAPIDefaultExecutionRole
        - Arn
      Runtime: !Ref ProgrammingLanguage
      MemorySize: 512
      Timeout: 60
      Environment:
        Variables:
          SP_API_APP_CREDENTIALS_SECRET_ARN: !Ref SPAPIAppCredentials
          REFRESH_TOKEN: !Ref RefreshToken
  SPAPISubscribeNotificationsLambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: !Join
        - '-'
        - - SPAPISubscribeNotifications
          - !Ref RandomSuffix
      Description: SP-API Subscribe Notifications Lambda function
      Code:
        S3Bucket: !Ref ArtifactsS3BucketName
        S3Key: !Ref LambdaFunctionsCodeS3Key
      Handler: !Ref SPAPISubscribeNotificationsHandler
      Role: !GetAtt
        - SPAPIDefaultExecutionRole
        - Arn
      Runtime: !Ref ProgrammingLanguage
      MemorySize: 512
      Timeout: 60
      Environment:
        Variables:
          SP_API_APP_CREDENTIALS_SECRET_ARN: !Ref SPAPIAppCredentials
          SQS_QUEUE_ARN: !GetAtt
            - SPAPINotificationsQueue
            - Arn
  SPAPISolicitationSchedulerLambdaExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Join
        - '-'
        - - SPAPISolicitationSchedulerLambdaExecutionRole
          - !Ref RandomSuffix
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - !Sub 'arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      Policies:
        - PolicyName: SQSPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'SQS:DeleteMessage'
                  - 'SQS:GetQueueAttributes'
                  - 'SQS:ReceiveMessage'
                Resource: !GetAtt
                  - SPAPINotificationsQueue
                  - Arn
        - PolicyName: EventBridgePolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'scheduler:GetSchedule'
                  - 'scheduler:CreateSchedule'
                  - 'iam:PassRole'
                Resource: '*'
  SPAPIGetSolicitationActionsLambdaExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Join
        - '-'
        - - SPAPIGetSolicitationActionsLambdaExecutionRole
          - !Ref RandomSuffix
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - !Sub 'arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      Policies:
        - PolicyName: SecretsReaderPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: 'secretsmanager:GetSecretValue'
                Resource:
                  - !Ref SPAPIAppCredentials
        - PolicyName: EventBridgePolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'scheduler:DeleteSchedule'
                Resource: '*'
  SPAPIDefaultExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Join
        - '-'
        - - SPAPIDefaultExecutionRole
          - !Ref RandomSuffix
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - !Sub 'arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      Policies:
        - PolicyName: SecretsReaderPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: 'secretsmanager:GetSecretValue'
                Resource:
                  - !Ref SPAPIAppCredentials
  SPAPISolicitationsSchedulerRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Join
        - '-'
        - - SPAPISolicitationsSchedulerRole
          - !Ref RandomSuffix
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - scheduler.amazonaws.com
            Condition:
              StringEquals:
                'aws:SourceAccount': !Ref AWS::AccountId
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: StepFunctionsPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: 'states:StartExecution'
                Resource: !Ref SPAPIStateMachine
  SPAPINotificationsDeadLetterQueue:
    Type: 'AWS::SQS::Queue'
    Properties:
      QueueName: !Join
        - '-'
        - - sp-api-notifications-dead-letter-queue
          - !Ref RandomSuffix
      VisibilityTimeout: 60
  SPAPINotificationsQueue:
    Type: 'AWS::SQS::Queue'
    Properties:
      QueueName: !Join
        - '-'
        - - sp-api-notifications-queue
          - !Ref RandomSuffix
      VisibilityTimeout: 60
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt
          - SPAPINotificationsDeadLetterQueue
          - Arn
        maxReceiveCount: 5
  SPAPINotificationsQueuePolicy:
    Type: 'AWS::SQS::QueuePolicy'
    Properties:
      Queues:
        - !Ref SPAPINotificationsQueue
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - 'SQS:SendMessage'
              - 'SQS:GetQueueAttributes'
            Resource: !GetAtt
              - SPAPINotificationsQueue
              - Arn
            Principal:
              AWS:
                - '437568002678'
  SolicitationSchedulerEventSourceMapping:
    Type: 'AWS::Lambda::EventSourceMapping'
    Properties:
      BatchSize: 1
      Enabled: true
      EventSourceArn: !GetAtt
        - SPAPINotificationsQueue
        - Arn
      FunctionName: !GetAtt
        - SPAPISolicitationSchedulerLambdaFunction
        - Arn
  SPAPIStateMachine:
    Type: 'AWS::StepFunctions::StateMachine'
    Properties:
      StateMachineName: !Join
        - '-'
        - - SPAPIStateMachine
          - !Ref RandomSuffix
      StateMachineType: STANDARD
      DefinitionS3Location:
        Bucket: !Ref ArtifactsS3BucketName
        Key: !Ref StepFunctionsStateMachineDefinitionS3Key
      DefinitionSubstitutions:
        GetSolicitationActionsLambdaFunctionArn: !GetAtt
          - SPAPIGetSolicitationActionsLambdaFunction
          - Arn
        SubmitSolicitationLambdaFunctionArn: !GetAtt
          - SPAPISubmitSolicitationLambdaFunction
          - Arn
      RoleArn: !GetAtt
        - SPAPIStateMachineExecutionRole
        - Arn
  SPAPIStateMachineExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: LambdaInvokePolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'lambda:InvokeFunction'
                Resource:
                  - !GetAtt
                    - SPAPIGetSolicitationActionsLambdaFunction
                    - Arn
                  - !GetAtt
                    - SPAPISubmitSolicitationLambdaFunction
                    - Arn